# Generated by Django 3.2.3 on 2021-09-30 20:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='required and unique', max_length=255, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='select <b>parent</b> category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='automatically generated from name', max_length=255, unique=True, verbose_name='category safe URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='product description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='required', max_length=255, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='web_id',
            field=models.CharField(blank=True, default='', help_text='product web ID - must be unique', max_length=50, null=True, unique=True, verbose_name='product website ID'),
        ),
    ]
