# Generated by Django 3.2.3 on 2021-10-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinventory',
            old_name='product_attribute_values',
            new_name='attribute_values',
        ),
    ]
