# Generated by Django 3.2.3 on 2021-10-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_product_attribute_values_productinventory_attribute_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(help_text='required', max_length=255, verbose_name='attribute name'),
        ),
    ]
