# Generated by Django 3.2.3 on 2021-09-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_web_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='web_id',
            field=models.CharField(blank=True, help_text='product web ID - must be unique', max_length=50, null=True, unique=True, verbose_name='product website ID'),
        ),
    ]
