# Generated by Django 3.2.3 on 2021-09-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_web_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='web_id',
            field=models.CharField(help_text='product web ID - must be unique', max_length=50, unique=True, verbose_name='product website ID'),
        ),
    ]
